services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production.docker
    ports:
      - 8000:8000
    volumes:
      - ./logs/docker:/usr/src/app/logs:z
    depends_on:
      redis_service:
        condition: service_started
  redis_service:
    image: redis
    ports:
      - 6379:6379